/*
 * SPDX-License-Identifier: MIT
 *
 * OpenMV imlib-only board configuration compatibility include.
 *
 */

#ifndef __OMV_BOARDCONFIG_H__
#define __OMV_BOARDCONFIG_H__

#include "boardconfig.h"

#define OMV_BOARD_ARCH             ESP_VISION_BOARD_ARCH
#define OMV_BOARD_TYPE             ESP_VISION_BOARD_TYPE
#define OMV_PORT_ESP32             ESP_VISION_PORT_ESP32

#define OMV_PROFILER_ENABLE        ESP_VISION_IMLIB_PROFILER_ENABLE
#define OMV_GPU_ENABLE             ESP_VISION_IMLIB_GPU_ENABLE
#define OMV_JPEG_CODEC_ENABLE      ESP_VISION_IMLIB_JPEG_CODEC_ENABLE

#define OMV_DMA_ALIGNMENT          ESP_VISION_DMA_ALIGNMENT

#define OMV_JPEG_QUALITY_LOW       ESP_VISION_JPEG_QUALITY_LOW
#define OMV_JPEG_QUALITY_HIGH      ESP_VISION_JPEG_QUALITY_HIGH
#define OMV_JPEG_QUALITY_THRESHOLD ESP_VISION_JPEG_QUALITY_THRESHOLD

#define OMV_RAW_PREVIEW_ENABLE     ESP_VISION_RAW_PREVIEW_ENABLE
#define OMV_RAW_PREVIEW_WIDTH      ESP_VISION_RAW_PREVIEW_WIDTH
#define OMV_RAW_PREVIEW_HEIGHT     ESP_VISION_RAW_PREVIEW_HEIGHT

#endif /* __OMV_BOARDCONFIG_H__ */
