#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "ESP32-S3-EYE"
#endif

#ifndef MICROPY_HW_MCU_NAME
#define MICROPY_HW_MCU_NAME "ESP32S3"
#endif

#define MICROPY_HW_USB_MANUFACTURER_STRING "ESP-VISION"
#define MICROPY_HW_USB_PRODUCT_FS_STRING "ESP32-S3-EYE MicroPython"
#define MICROPY_HW_ENABLE_USBDEV (1)
#define MICROPY_HW_USB_CDC (1)
#define MICROPY_HW_ESP_USB_SERIAL_JTAG (0)
#define MICROPY_HW_ENABLE_USB_RUNTIME_DEVICE (0)
#define MICROPY_HW_ENABLE_UART_REPL (1)

#define MICROPY_HW_USB_MSC (1)
#define MICROPY_HW_USB_MSC_INTERFACE_STRING "ESP32-S3-EYE Flash"
#define MICROPY_HW_USB_MSC_INQUIRY_VENDOR_STRING "ESPVIS"
#define MICROPY_HW_USB_MSC_INQUIRY_PRODUCT_STRING "S3-EYE Flash"
#define MICROPY_HW_USB_MSC_INQUIRY_REVISION_STRING "1.00"

#define MICROPY_PY_ESPNOW (0)
#define MICROPY_HW_ENABLE_SDCARD (0)
#define MICROPY_PY_BLUETOOTH (0)

#ifndef MICROPY_PY_NETWORK_WLAN
#define MICROPY_PY_NETWORK_WLAN (1)
#endif

#define MICROPY_HW_I2C0_SCL (5)
#define MICROPY_HW_I2C0_SDA (4)

// TinyUSB's FreeRTOS OSAL can call portYIELD_FROM_ISR() while FreeRTOS.h is
// still including the Xtensa port headers. Define this trace hook before
// portmacro.h expands it; FreeRTOS.h normally provides the same no-op later.
#ifndef traceISR_EXIT_TO_SCHEDULER
#define traceISR_EXIT_TO_SCHEDULER()
#endif
