#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "ESP-VISION-TEMPLATE"
#endif

#ifndef MICROPY_HW_MCU_NAME
#define MICROPY_HW_MCU_NAME "ESP32P4"
#endif

#define MICROPY_HW_USB_MANUFACTURER_STRING "ESP-VISION"
#define MICROPY_HW_USB_PRODUCT_FS_STRING "ESP-VISION Template MicroPython"

#define MICROPY_HW_USB_MSC (0)
#define MICROPY_HW_ENABLE_SDCARD (0)
#define MICROPY_HW_ENABLE_UART_REPL (1)

#define MICROPY_PY_ESPNOW (0)
#define MICROPY_PY_BLUETOOTH (0)

#ifndef MICROPY_PY_NETWORK_WLAN
#define MICROPY_PY_NETWORK_WLAN (0)
#endif
