# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Any, Callable, Sequence, overload

BINARY: int
GRAYSCALE: int
RGB565: int
BAYER: int
YUV422: int
JPEG: int
PNG: int

PALETTE_RAINBOW: int
PALETTE_IRONBOW: int
PALETTE_DEPTH: int
PALETTE_EVT_DARK: int
PALETTE_EVT_LIGHT: int

AREA: int
BILINEAR: int
BICUBIC: int
HMIRROR: int
VFLIP: int
TRANSPOSE: int
CENTER: int
EXTRACT_RGB_CHANNEL_FIRST: int
APPLY_COLOR_PALETTE_FIRST: int
SCALE_ASPECT_KEEP: int
SCALE_ASPECT_EXPAND: int
SCALE_ASPECT_IGNORE: int
BLACK_BACKGROUND: int
ROTATE_90: int
ROTATE_180: int
ROTATE_270: int

JPEG_SUBSAMPLING_AUTO: int
JPEG_SUBSAMPLING_444: int
JPEG_SUBSAMPLING_422: int
JPEG_SUBSAMPLING_420: int

SEARCH_EX: int
SEARCH_DS: int
EDGE_CANNY: int
EDGE_SIMPLE: int
CORNER_FAST: int
CORNER_AGAST: int
TAG16H5: int
TAG25H7: int
TAG25H9: int
TAG36H10: int
TAG36H11: int

Color = int | tuple[int, int, int]
Point = tuple[int, int]
LineTuple = tuple[int, int, int, int]
CircleTuple = tuple[int, int, int]
EllipseTuple = tuple[int, int, int, int, int]
Rect = tuple[int, int, int, int]
LineLike = LineTuple | Sequence[int]
CircleLike = CircleTuple | Sequence[int]
EllipseLike = EllipseTuple | Sequence[int]
RectLike = Rect | Sequence[int]
Threshold = tuple[int, int] | tuple[int, int, int, int, int, int]
Thresholds = Sequence[Threshold]


class line:
    def line(self) -> LineTuple: ...
    def x1(self) -> int: ...
    def y1(self) -> int: ...
    def x2(self) -> int: ...
    def y2(self) -> int: ...
    def length(self) -> int: ...
    def magnitude(self) -> int: ...
    def theta(self) -> int: ...
    def rho(self) -> int: ...


class circle:
    def circle(self) -> CircleTuple: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def r(self) -> int: ...
    def magnitude(self) -> int: ...


class rect:
    def corners(self) -> tuple[Point, Point, Point, Point]: ...
    def rect(self) -> Rect: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def w(self) -> int: ...
    def h(self) -> int: ...
    def magnitude(self) -> int: ...


class blob:
    def corners(self) -> tuple[Point, Point, Point, Point]: ...
    def min_corners(self) -> tuple[Point, Point, Point, Point]: ...
    def rect(self) -> Rect: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def w(self) -> int: ...
    def h(self) -> int: ...
    def pixels(self) -> int: ...
    def cx(self) -> int: ...
    def cxf(self) -> float: ...
    def cy(self) -> int: ...
    def cyf(self) -> float: ...
    def rotation(self) -> float: ...
    def rotation_deg(self) -> float: ...
    def rotation_rad(self) -> float: ...
    def code(self) -> int: ...
    def count(self) -> int: ...
    def perimeter(self) -> int: ...
    def roundness(self) -> float: ...
    def elongation(self) -> float: ...
    def area(self) -> int: ...
    def density(self) -> float: ...
    def extent(self) -> float: ...
    def compactness(self) -> float: ...
    def solidity(self) -> float: ...
    def convexity(self) -> float: ...
    def x_hist_bins(self) -> list[int]: ...
    def y_hist_bins(self) -> list[int]: ...
    def major_axis_line(self) -> LineTuple: ...
    def minor_axis_line(self) -> LineTuple: ...
    def enclosing_circle(self) -> CircleTuple: ...
    def enclosed_ellipse(self) -> EllipseTuple: ...


class qrcode:
    def corners(self) -> tuple[Point, Point, Point, Point]: ...
    def rect(self) -> Rect: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def w(self) -> int: ...
    def h(self) -> int: ...
    def payload(self) -> str: ...
    def version(self) -> int: ...
    def ecc_level(self) -> int: ...
    def mask(self) -> int: ...
    def data_type(self) -> int: ...
    def eci(self) -> int: ...
    def is_numeric(self) -> bool: ...
    def is_alphanumeric(self) -> bool: ...
    def is_binary(self) -> bool: ...
    def is_kanji(self) -> bool: ...


class apriltag:
    corners: tuple[Point, Point, Point, Point]
    rect: Rect
    x: int
    y: int
    w: int
    h: int
    area: int
    id: int
    family: int
    name: str
    cx: int
    cxf: float
    cy: int
    cyf: float
    rotation: float
    decision_margin: float
    hamming: int
    goodness: float
    x_translation: float
    y_translation: float
    z_translation: float
    x_rotation: float
    y_rotation: float
    z_rotation: float


class histogram:
    def bins(self) -> list[float]: ...
    def l_bins(self) -> list[float]: ...
    def a_bins(self) -> list[float]: ...
    def b_bins(self) -> list[float]: ...
    def get_percentile(self, p: float) -> percentile: ...
    def get_threshold(self) -> threshold: ...
    def get_stats(self) -> statistics: ...
    def get_statistics(self) -> statistics: ...
    def statistics(self) -> statistics: ...


class percentile:
    def value(self) -> int: ...
    def l_value(self) -> int: ...
    def a_value(self) -> int: ...
    def b_value(self) -> int: ...


class threshold:
    def value(self) -> int: ...
    def l_value(self) -> int: ...
    def a_value(self) -> int: ...
    def b_value(self) -> int: ...


class statistics:
    def mean(self) -> int: ...
    def median(self) -> int: ...
    def mode(self) -> int: ...
    def stdev(self) -> int: ...
    def min(self) -> int: ...
    def max(self) -> int: ...
    def lq(self) -> int: ...
    def uq(self) -> int: ...
    def l_mean(self) -> int: ...
    def l_median(self) -> int: ...
    def l_mode(self) -> int: ...
    def l_stdev(self) -> int: ...
    def l_min(self) -> int: ...
    def l_max(self) -> int: ...
    def l_lq(self) -> int: ...
    def l_uq(self) -> int: ...
    def a_mean(self) -> int: ...
    def a_median(self) -> int: ...
    def a_mode(self) -> int: ...
    def a_stdev(self) -> int: ...
    def a_min(self) -> int: ...
    def a_max(self) -> int: ...
    def a_lq(self) -> int: ...
    def a_uq(self) -> int: ...
    def b_mean(self) -> int: ...
    def b_median(self) -> int: ...
    def b_mode(self) -> int: ...
    def b_stdev(self) -> int: ...
    def b_min(self) -> int: ...
    def b_max(self) -> int: ...
    def b_lq(self) -> int: ...
    def b_uq(self) -> int: ...


class Image:
    @overload
    def __init__(self, path: str, *, copy_to_fb: bool = False) -> None: ...
    @overload
    def __init__(
        self,
        width: int,
        height: int,
        pixformat: int,
        *,
        buffer: Any | None = None,
        copy_to_fb: bool = False,
    ) -> None: ...
    @overload
    def __init__(self, array: Any, *, buffer: Any | None = None, copy_to_fb: bool = False) -> None: ...

    def width(self) -> int: ...
    def height(self) -> int: ...
    def format(self) -> int: ...
    def size(self) -> int: ...
    def bytearray(self) -> bytearray: ...
    def get_pixel(self, x: int, y: int, *, rgbtuple: bool = True) -> Any: ...
    def set_pixel(self, x: int, y: int, pixel: Color) -> Image: ...
    def flush(self) -> None: ...
    def save(self, path: str, *, roi: RectLike | None = None, quality: int = 50) -> Image: ...

    def copy(self, **kwargs: Any) -> Image: ...
    def crop(self, **kwargs: Any) -> Image: ...
    def scale(self, **kwargs: Any) -> Image: ...
    def compress(self, **kwargs: Any) -> Image: ...
    def to_bitmap(self, **kwargs: Any) -> Image: ...
    def to_grayscale(self, **kwargs: Any) -> Image: ...
    def to_rgb565(self, **kwargs: Any) -> Image: ...
    def to_rainbow(self, **kwargs: Any) -> Image: ...
    def to_ironbow(self, **kwargs: Any) -> Image: ...
    def to_jpeg(self, **kwargs: Any) -> Image: ...
    def to_png(self, **kwargs: Any) -> Image: ...

    def clear(self, *, mask: Image | None = None) -> Image: ...
    @overload
    def draw_line(self, x0: int, y0: int, x1: int, y1: int, color: Color = ..., thickness: int = 1) -> Image: ...
    @overload
    def draw_line(self, line: LineLike, color: Color = ..., thickness: int = 1) -> Image: ...
    @overload
    def draw_rectangle(
        self,
        x: int,
        y: int,
        w: int,
        h: int,
        color: Color = ...,
        thickness: int = 1,
        fill: bool = False,
    ) -> Image: ...
    @overload
    def draw_rectangle(self, rect: RectLike, color: Color = ..., thickness: int = 1, fill: bool = False) -> Image: ...
    @overload
    def draw_circle(
        self,
        x: int,
        y: int,
        r: int,
        color: Color = ...,
        thickness: int = 1,
        fill: bool = False,
    ) -> Image: ...
    @overload
    def draw_circle(self, circle: CircleLike, color: Color = ..., thickness: int = 1, fill: bool = False) -> Image: ...
    @overload
    def draw_ellipse(
        self,
        x: int,
        y: int,
        rx: int,
        ry: int,
        rotation: int,
        color: Color = ...,
        thickness: int = 1,
        fill: bool = False,
    ) -> Image: ...
    @overload
    def draw_ellipse(
        self,
        ellipse: EllipseLike,
        color: Color = ...,
        thickness: int = 1,
        fill: bool = False,
    ) -> Image: ...
    def draw_string(
        self,
        x: int,
        y: int,
        text: str,
        color: Color = ...,
        scale: float = 1.0,
        x_spacing: int = 0,
        y_spacing: int = 0,
        mono_space: bool = True,
        char_rotation: int = 0,
        char_hmirror: bool = False,
        char_vflip: bool = False,
        string_rotation: int = 0,
        string_hmirror: bool = False,
        string_vflip: bool = False,
    ) -> Image: ...
    def draw_cross(self, x: int, y: int, color: Color = ..., size: int = 5, thickness: int = 1) -> Image: ...
    @overload
    def draw_arrow(
        self,
        x0: int,
        y0: int,
        x1: int,
        y1: int,
        color: Color = ...,
        size: int = 10,
        thickness: int = 1,
    ) -> Image: ...
    @overload
    def draw_arrow(self, line: LineLike, color: Color = ..., size: int = 10, thickness: int = 1) -> Image: ...
    def draw_edges(
        self,
        corners: Sequence[Point],
        color: Color = ...,
        size: int = 0,
        thickness: int = 1,
        fill: bool = False,
    ) -> Image: ...
    def draw_keypoints(
        self,
        keypoints: Sequence[tuple[int, int, int]] | Any,
        color: Color = ...,
        size: int = 10,
        thickness: int = 1,
        fill: bool = False,
    ) -> Image: ...
    def draw_image(self, image: Image | Color | int, x: int = 0, y: int = 0, **kwargs: Any) -> Image: ...

    def binary(
        self,
        thresholds: Thresholds,
        *,
        invert: bool = False,
        zero: bool = False,
        mask: Image | None = None,
        to_bitmap: bool = False,
        copy: bool = False,
    ) -> Image: ...
    def invert(self) -> Image: ...
    def erode(self, ksize: int, *, threshold: int = 0, mask: Image | None = None) -> Image: ...
    def dilate(self, ksize: int, *, threshold: int = 0, mask: Image | None = None) -> Image: ...
    def open(self, ksize: int, *, threshold: int = 0, mask: Image | None = None) -> Image: ...
    def close(self, ksize: int, *, threshold: int = 0, mask: Image | None = None) -> Image: ...
    def difference(self, image: Image | Color | int, x: int = 0, y: int = 0, **kwargs: Any) -> Image: ...
    def histeq(self, *, adaptive: bool = False, clip_limit: float = -1, mask: Image | None = None) -> Image: ...
    def mean(
        self,
        ksize: int,
        *,
        threshold: bool = False,
        offset: int = 0,
        invert: bool = False,
        mask: Image | None = None,
    ) -> Image: ...
    def median(self, ksize: int, **kwargs: Any) -> Image: ...
    def mode(self, ksize: int, **kwargs: Any) -> Image: ...
    def midpoint(self, ksize: int, **kwargs: Any) -> Image: ...
    def morph(self, ksize: int, kernel: Sequence[int], **kwargs: Any) -> Image: ...
    def blur(self, ksize: int, **kwargs: Any) -> Image: ...
    def gaussian(self, ksize: int, **kwargs: Any) -> Image: ...
    def gaussian_blur(self, ksize: int, **kwargs: Any) -> Image: ...
    def laplacian(self, ksize: int, **kwargs: Any) -> Image: ...
    def bilateral(self, ksize: int, **kwargs: Any) -> Image: ...

    def get_histogram(self, thresholds: Thresholds | None = None, **kwargs: Any) -> histogram: ...
    def get_hist(self, thresholds: Thresholds | None = None, **kwargs: Any) -> histogram: ...
    def histogram(self, thresholds: Thresholds | None = None, **kwargs: Any) -> histogram: ...
    def get_statistics(self, thresholds: Thresholds | None = None, **kwargs: Any) -> statistics: ...
    def get_stats(self, thresholds: Thresholds | None = None, **kwargs: Any) -> statistics: ...
    def statistics(self, thresholds: Thresholds | None = None, **kwargs: Any) -> statistics: ...
    def get_regression(self, thresholds: Thresholds, **kwargs: Any) -> line | None: ...
    def find_blobs(
        self,
        thresholds: Thresholds,
        *,
        invert: bool = False,
        roi: RectLike | None = None,
        x_stride: int = 2,
        y_stride: int = 1,
        area_threshold: int = 10,
        pixels_threshold: int = 10,
        merge: bool = False,
        margin: int = 0,
        threshold_cb: Callable[[blob], bool] | None = None,
        merge_cb: Callable[[blob, blob], bool] | None = None,
        x_hist_bins_max: int = 0,
        y_hist_bins_max: int = 0,
    ) -> list[blob]: ...
    def find_lines(self, **kwargs: Any) -> list[line]: ...
    def find_circles(self, **kwargs: Any) -> list[circle]: ...
    def find_rects(self, **kwargs: Any) -> list[rect]: ...
    def find_qrcodes(self, **kwargs: Any) -> list[qrcode]: ...
    def find_apriltags(
        self,
        *,
        roi: RectLike | None = None,
        families: int = ...,
        fx: float = ...,
        fy: float = ...,
        cx: float = ...,
        cy: float = ...,
        pose: bool = True,
    ) -> list[apriltag]: ...


def binary_to_grayscale(pixel: int) -> int: ...
def binary_to_rgb(pixel: int) -> tuple[int, int, int]: ...
def binary_to_lab(pixel: int) -> tuple[int, int, int]: ...
def binary_to_yuv(pixel: int) -> tuple[int, int, int]: ...
def grayscale_to_binary(pixel: int) -> int: ...
def grayscale_to_rgb(pixel: int) -> tuple[int, int, int]: ...
def grayscale_to_lab(pixel: int) -> tuple[int, int, int]: ...
def grayscale_to_yuv(pixel: int) -> tuple[int, int, int]: ...
def rgb_to_binary(pixel: Color) -> int: ...
def rgb_to_grayscale(pixel: Color) -> int: ...
def rgb_to_lab(pixel: Color) -> tuple[int, int, int]: ...
def rgb_to_yuv(pixel: Color) -> tuple[int, int, int]: ...
def lab_to_binary(pixel: Sequence[int]) -> int: ...
def lab_to_grayscale(pixel: Sequence[int]) -> int: ...
def lab_to_rgb(pixel: Sequence[int]) -> tuple[int, int, int]: ...
def lab_to_yuv(pixel: Sequence[int]) -> tuple[int, int, int]: ...
def yuv_to_binary(pixel: Sequence[int]) -> int: ...
def yuv_to_grayscale(pixel: Sequence[int]) -> int: ...
def yuv_to_rgb(pixel: Sequence[int]) -> tuple[int, int, int]: ...
def yuv_to_lab(pixel: Sequence[int]) -> tuple[int, int, int]: ...
