# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal, overload

from image import Image

FILE_STREAM: int
MEMORY_STREAM: int

ImageInfo = tuple[int, int, int]


class ImageIO:
    @overload
    def __init__(self, stream: str, mode: Literal["r", "w"]) -> None: ...
    @overload
    def __init__(self, stream: ImageInfo, count: int) -> None: ...
    def __del__(self) -> None: ...
    def type(self) -> int: ...
    def is_closed(self) -> bool: ...
    def count(self) -> int: ...
    def offset(self) -> int: ...
    def version(self) -> int | None: ...
    def buffer_size(self) -> int | None: ...
    def size(self) -> int: ...
    def write(self, image: Image) -> ImageIO: ...
    def read(self, copy_to_fb: bool = True, *, loop: bool = True, pause: bool = True) -> Image | None: ...
    def seek(self, offset: int) -> ImageIO: ...
    def sync(self) -> ImageIO: ...
    def close(self) -> None: ...
