# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Any, TypedDict

from image import Image

GRAYSCALE: int
RGB565: int
QQVGA: int
QVGA: int


class SensorStatus(TypedDict):
    ready: bool
    id: int
    width: int
    height: int
    pixformat: int
    hmirror: bool
    vflip: bool
    raw_width: int
    raw_height: int
    active_width: int
    active_height: int


def reset() -> None: ...
def shutdown(enable: bool = True) -> None: ...
def set_pixformat(pixformat: int) -> None: ...
def get_pixformat() -> int: ...
def set_framesize(framesize: int) -> None: ...
def get_framesize() -> int: ...
def width() -> int: ...
def height() -> int: ...
def get_id() -> int: ...
def set_hmirror(enable: bool) -> None: ...
def get_hmirror() -> bool: ...
def set_vflip(enable: bool) -> None: ...
def get_vflip() -> bool: ...
def skip_frames(time: int = 0, n: int = 0) -> None: ...
def snapshot(buffer: Any | None = None) -> Image: ...
def status() -> SensorStatus: ...
