DEFAULT:
  perform_check: yes
  allowed_licenses:
    - Apache-2.0
  license_for_new_files: Apache-2.0
  new_notice_c: |
    /*
     * SPDX-FileCopyrightText: {years} Espressif Systems (Shanghai) CO LTD
     *
     * SPDX-License-Identifier: {license}
     */
  new_notice_python: |
    # SPDX-FileCopyrightText: {years} Espressif Systems (Shanghai) CO LTD
    # SPDX-License-Identifier: {license}
  espressif_copyright: '{years} Espressif Systems (Shanghai) CO LTD'

ignore:
  perform_check: no
  include:
    - 'build/**/*'
    - 'dist/**/*'
    - 'lib/micropython/**/*'
    - 'vscode-extension/node_modules/**/*'
    - 'vscode-extension/out/**/*'
    - 'vscode-extension/package-lock.json'
    - 'vscode-extension/package.json'
    - 'vscode-extension/tsconfig.json'
    - 'vscode-extension/.vscode/**/*'
    - 'vscode-extension/.vscodeignore'
    - 'vscode-extension/README.md'
    - 'vscode-extension/*.vsix'
    - 'patches/**/*'
    - '**/*.patch'
    - '**/*.py'
    - 'tools/ci/check_copyright_ignore.txt'
