# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

"""Generate board support tables from firmware configuration files.

Board capability data is derived in ``docs/board_model.py`` (the single source
of derived truth, shared with the website's config.toml generator). This module
is just the RST renderer for that data.
"""

from pathlib import Path

from board_model import board_info
from gen_api import _write_if_changed
from targets import TARGET_CAPABILITIES

DOCS_DIR = Path(__file__).resolve().parent
LANGUAGES = ('en', 'zh_CN')


def _render(lang):
    labels = {
        'en': {
            'picture': 'Picture',
            'board': 'Board',
            'chip': 'Chip',
            'support': 'ESP-VISION support',
            'supported': 'Supported',
            'modules': 'Modules',
            'micropython': 'MicroPython',
            'vision': 'Vision',
            'note': (
                'The support summary is generated from ``mpconfigport.h``, '
                'each board ``mpconfigboard.h`` and ``imlib_config.h``, and '
                'the chip-specific module selection.'
            ),
        },
        'zh_CN': {
            'picture': '图片',
            'board': '开发板',
            'chip': '芯片',
            'support': 'ESP-VISION 支持情况',
            'supported': '支持',
            'modules': '模块',
            'micropython': 'MicroPython',
            'vision': '视觉能力',
            'note': (
                '支持摘要根据 ``mpconfigport.h``、各开发板的 '
                '``mpconfigboard.h`` 与 ``imlib_config.h``，以及芯片相关的'
                '模块选择自动生成。'
            ),
        },
    }[lang]
    out = [
        '.. This file is generated by docs/gen_board_support.py.',
        '.. Do not edit by hand; edit the firmware configuration instead.',
        '',
        '.. list-table::',
        '   :header-rows: 1',
        '   :widths: 20 20 12 48',
        '',
        '   * - {}'.format(labels['picture']),
        '     - {}'.format(labels['board']),
        '     - {}'.format(labels['chip']),
        '     - {}'.format(labels['support']),
    ]
    for target, capabilities in TARGET_CAPABILITIES.items():
        for board in capabilities['boards']:
            info = board_info(board, target)
            status = labels['supported']
            board_name = info['name']
            if info['url']:
                board_name = '`{} <{}>`__'.format(info['name'], info['url'])
            support = (
                '**{supported}** | {modules}: ``{module_values}`` | '
                '{micropython}: {port_values} | {vision}: {vision_values}'
            ).format(
                supported=status,
                modules=labels['modules'],
                module_values='``, ``'.join(info['modules']),
                micropython=labels['micropython'],
                port_values=', '.join(info['port_features']),
                vision=labels['vision'],
                vision_values=', '.join(info['imlib_features']),
            )
            out.extend(
                [
                    '   * - .. image:: {}'.format(info['image']),
                    '          :width: 180px',
                    '          :alt: {}'.format(info['name']),
                    '     - {}'.format(board_name),
                    '     - ``{}``'.format(info['chip']),
                    '     - {}'.format(support),
                ]
            )
    out.extend(['', '.. note::', '', '   {}'.format(labels['note']), ''])
    return '\n'.join(out)


def generate(app=None):  # noqa: ARG001
    for lang in LANGUAGES:
        out_dir = DOCS_DIR / lang / 'target-support' / '_generated'
        out_dir.mkdir(parents=True, exist_ok=True)
        _write_if_changed(str(out_dir / 'boards.rst'), _render(lang))


if __name__ == '__main__':
    generate()
    print('Generated board support tables.')
