/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ESP_VISION_IMLIB_CONFIG_H
#define ESP_VISION_IMLIB_CONFIG_H

#ifndef OMV_NO_GPL
#define OMV_NO_GPL
#endif

#define IMLIB_ENABLE_BINARY_OPS
#define IMLIB_ENABLE_MATH_OPS
#define IMLIB_ENABLE_LAB_LUT

#define IMLIB_ENABLE_MEAN
#define IMLIB_ENABLE_MEDIAN
#define IMLIB_ENABLE_MODE
#define IMLIB_ENABLE_MIDPOINT
#define IMLIB_ENABLE_MORPH
#define IMLIB_ENABLE_GAUSSIAN
#define IMLIB_ENABLE_LAPLACIAN
#define IMLIB_ENABLE_BILATERAL

#define IMLIB_ENABLE_FIND_LINES
#define IMLIB_ENABLE_FIND_CIRCLES
#define IMLIB_FIND_TEMPLATE

#endif /* ESP_VISION_IMLIB_CONFIG_H */
