name: Test IDF Container

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v6.0
    steps:
      - name: Check IDF
        run: idf.py --version
